[package]
name = "packing-drawings"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = {version = "0.13.1", features = ["tokio"]}
tokio = { version = "1.45.1", features = ["full"] }
tokio-util = "0.7.15"